# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: master.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'master.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x12\x06master\"%\n\x10HeartbeatRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"p\n\x11HeartbeatResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x1a\n\x12\x63urrent_task_count\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x1c\n\x14in_progress_task_ids\x18\x04 \x03(\t\"~\n\x11TaskUpdateRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"*\n\x12TaskUpdateResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"(\n\x13WorkerStatusRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x9f\x01\n\x14WorkerStatusResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0elast_heartbeat\x18\x03 \x01(\x03\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\x12\x1a\n\x12\x63urrent_task_count\x18\x05 \x01(\x05\x12\x1c\n\x14in_progress_task_ids\x18\x06 \x03(\t2\xa8\x01\n\rMasterService\x12I\n\x10ReportTaskUpdate\x12\x19.master.TaskUpdateRequest\x1a\x1a.master.TaskUpdateResponse\x12L\n\x0fGetWorkerStatus\x12\x1b.master.WorkerStatusRequest\x1a\x1c.master.WorkerStatusResponse2Q\n\rWorkerService\x12@\n\tHeartbeat\x12\x18.master.HeartbeatRequest\x1a\x19.master.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=24
  _globals['_HEARTBEATREQUEST']._serialized_end=61
  _globals['_HEARTBEATRESPONSE']._serialized_start=63
  _globals['_HEARTBEATRESPONSE']._serialized_end=175
  _globals['_TASKUPDATEREQUEST']._serialized_start=177
  _globals['_TASKUPDATEREQUEST']._serialized_end=303
  _globals['_TASKUPDATERESPONSE']._serialized_start=305
  _globals['_TASKUPDATERESPONSE']._serialized_end=347
  _globals['_WORKERSTATUSREQUEST']._serialized_start=349
  _globals['_WORKERSTATUSREQUEST']._serialized_end=389
  _globals['_WORKERSTATUSRESPONSE']._serialized_start=392
  _globals['_WORKERSTATUSRESPONSE']._serialized_end=551
  _globals['_MASTERSERVICE']._serialized_start=554
  _globals['_MASTERSERVICE']._serialized_end=722
  _globals['_WORKERSERVICE']._serialized_start=724
  _globals['_WORKERSERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
