# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frontier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frontier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontier.proto\x12\x16shared.protos.frontier\"\x17\n\x08\x46rontier\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1e\n\x0f\x46rontierRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"/\n\x10\x46rontierResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2m\n\x0f\x46rontierService\x12Z\n\x05\x43rawl\x12\'.shared.protos.frontier.FrontierRequest\x1a(.shared.protos.frontier.FrontierResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRONTIER']._serialized_start=42
  _globals['_FRONTIER']._serialized_end=65
  _globals['_FRONTIERREQUEST']._serialized_start=67
  _globals['_FRONTIERREQUEST']._serialized_end=97
  _globals['_FRONTIERRESPONSE']._serialized_start=99
  _globals['_FRONTIERRESPONSE']._serialized_end=146
  _globals['_FRONTIERSERVICE']._serialized_start=148
  _globals['_FRONTIERSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
