# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import shared.protos.frontier.frontier_pb2 as frontier__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in frontier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrontierServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Crawl = channel.unary_unary(
                '/shared.protos.frontier.FrontierService/Crawl',
                request_serializer=frontier__pb2.FrontierRequest.SerializeToString,
                response_deserializer=frontier__pb2.FrontierResponse.FromString,
                _registered_method=True)


class FrontierServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Crawl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Crawl': grpc.unary_unary_rpc_method_handler(
                    servicer.Crawl,
                    request_deserializer=frontier__pb2.FrontierRequest.FromString,
                    response_serializer=frontier__pb2.FrontierResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shared.protos.frontier.FrontierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shared.protos.frontier.FrontierService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrontierService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Crawl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shared.protos.frontier.FrontierService/Crawl',
            frontier__pb2.FrontierRequest.SerializeToString,
            frontier__pb2.FrontierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
