# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frontier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frontier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontier.proto\x12\x16shared.protos.frontier\"?\n\x0f\x46rontierRequest\x12\x0b\n\x03url\x18\x01 \x03(\t\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x05\x12\x10\n\x08\x63rawl_id\x18\x03 \x01(\t\"\"\n\x10\x46rontierResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2t\n\x0f\x46rontierService\x12\x61\n\x0c\x43rawlRequest\x12\'.shared.protos.frontier.FrontierRequest\x1a(.shared.protos.frontier.FrontierResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRONTIERREQUEST']._serialized_start=42
  _globals['_FRONTIERREQUEST']._serialized_end=105
  _globals['_FRONTIERRESPONSE']._serialized_start=107
  _globals['_FRONTIERRESPONSE']._serialized_end=141
  _globals['_FRONTIERSERVICE']._serialized_start=143
  _globals['_FRONTIERSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
