AMQP_URL="amqp://admin:password@localhost/"
MAX_TASKS_THRESHOLD=5

MASTER_PROTO_SERVER="localhost:50052"
FRONTIER_PROTO_SERVER="localhost:50051"

MISSED_HBS_ALLOWED = 3
HEARTBEAT_INTERVAL = 5
HEARTBEAT_TIMEOUT = 15